/** Slugs портфеля Altacod — общий список для SEO и генерации изображений */
export const APP_SLUGS = [
  "altakid",
  "altanote",
  "altapens",
  "altatrade",
  "publisher",
  "neuromaster",
  "voensovet",
  "dacha-ai",
  "neurofriend",
  "ipra",
  "app-audit",
  "demand-pilot",
  "wibestyle",
  "orchestra",
  "multitool",
  "docbuddy",
  "lovebaby",
  "drinkbuddy",
  "school-trainer",
  "xintegra",
];

export const APP_IMAGE_META = [
  { slug: "altakid", title: "AltaKid", subtitle: "Родительский контроль", colors: ["#0ea5e9", "#6366f1"], icon: "🛡️" },
  { slug: "altanote", title: "AltaNote", subtitle: "Умные заметки", colors: ["#8b5cf6", "#ec4899"], icon: "📝" },
  { slug: "altapens", title: "AltaPens", subtitle: "Забота о близких", colors: ["#14b8a6", "#3b82f6"], icon: "💚" },
  { slug: "altatrade", title: "AltaTrade", subtitle: "Аналитика рынков", colors: ["#1e3a5f", "#0ea5e9"], icon: "📈" },
  { slug: "publisher", title: "Publisher", subtitle: "Контент и автопостинг", colors: ["#f59e0b", "#ef4444"], icon: "📣" },
  { slug: "neuromaster", title: "NeuroMaster", subtitle: "ИИ-инструменты", colors: ["#7c3aed", "#06b6d4"], icon: "✨" },
  { slug: "voensovet", title: "Voensovet", subtitle: "Помощь военным", colors: ["#1d4ed8", "#64748b"], icon: "🎖️" },
  { slug: "dacha-ai", title: "Любимая Дача", subtitle: "Сад и огород", colors: ["#22c55e", "#84cc16"], icon: "🌱" },
  { slug: "neurofriend", title: "NeuroFriend", subtitle: "Нейрособеседник", colors: ["#a855f7", "#f472b6"], icon: "💬" },
  { slug: "ipra", title: "ИПРА.РФ", subtitle: "Социальная поддержка", colors: ["#0d9488", "#2563eb"], icon: "🤝" },
  { slug: "app-audit", title: "App Audit", subtitle: "Готовность к релизу", colors: ["#f97316", "#eab308"], icon: "🔍" },
  { slug: "demand-pilot", title: "Demand Pilot", subtitle: "Спрос на продукт", colors: ["#6366f1", "#14b8a6"], icon: "🎯" },
  { slug: "wibestyle", title: "WibeStyle", subtitle: "Виртуальная примерка", colors: ["#ec4899", "#8b5cf6"], icon: "👗" },
  { slug: "orchestra", title: "Orchestra", subtitle: "Мультиагенты", colors: ["#334155", "#06b6d4"], icon: "🎼" },
  { slug: "multitool", title: "MultiTool", subtitle: "Агентная платформа", colors: ["#475569", "#7c3aed"], icon: "🔧" },
  { slug: "docbuddy", title: "DocBuddy", subtitle: "Для самозанятых", colors: ["#0284c7", "#10b981"], icon: "📋" },
  { slug: "lovebaby", title: "МалышAI", subtitle: "Родителям малышей", colors: ["#fb7185", "#fda4af"], icon: "👶" },
  { slug: "drinkbuddy", title: "DrinkBuddy", subtitle: "Компания для отдыха", colors: ["#f59e0b", "#b45309"], icon: "🍻" },
  { slug: "school-trainer", title: "School Trainer", subtitle: "Школьный тренажёр", colors: ["#3b82f6", "#22d3ee"], icon: "📚" },
  { slug: "xintegra", title: "Xintegra", subtitle: "Интегратор X", colors: ["#0f172a", "#38bdf8"], icon: "𝕏" },
];
